// Code generated by MockGen. DO NOT EDIT.
// Source: apis.go
//
// Generated by this command:
//
//	mockgen -package=apistest -source=apis.go -destination=apistest/apis.go .
//

// Package apistest is a generated GoMock package.
package apistest

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGithub is a mock of Github interface.
type MockGithub struct {
	ctrl     *gomock.Controller
	recorder *MockGithubMockRecorder
	isgomock struct{}
}

// MockGithubMockRecorder is the mock recorder for MockGithub.
type MockGithubMockRecorder struct {
	mock *MockGithub
}

// NewMockGithub creates a new mock instance.
func NewMockGithub(ctrl *gomock.Controller) *MockGithub {
	mock := &MockGithub{ctrl: ctrl}
	mock.recorder = &MockGithubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGithub) EXPECT() *MockGithubMockRecorder {
	return m.recorder
}

// AuthenticateAndWriteComment mocks base method.
func (m *MockGithub) AuthenticateAndWriteComment(fullRepoName string, issueNumber int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateAndWriteComment", fullRepoName, issueNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// AuthenticateAndWriteComment indicates an expected call of AuthenticateAndWriteComment.
func (mr *MockGithubMockRecorder) AuthenticateAndWriteComment(fullRepoName, issueNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateAndWriteComment", reflect.TypeOf((*MockGithub)(nil).AuthenticateAndWriteComment), fullRepoName, issueNumber)
}
